/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Bob.glb -o ..\components\Bob.jsx 
*/

import React from 'react';
import { useGLTF, useTexture } from '@react-three/drei';

export function Bob({ avatar, ...props }) {
  const { nodes, materials } = useGLTF('/models/Bob.glb');
  const texture = useTexture([avatar]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Eyes_Sphere.geometry} material={materials.Eyes} />
      <mesh geometry={nodes.Tooth_Cube001.geometry} material={materials.Tooth} />
      <mesh geometry={nodes.Body_Cube002.geometry}>
        <meshStandardMaterial map={texture[0]} />
      </mesh>
      <mesh geometry={nodes.Arms_Cube003.geometry} material={materials.Pink} />
      <mesh geometry={nodes.Head_Cube.geometry} material={materials.Pink} />
    </group>
  );
}

useGLTF.preload('/models/Bob.glb');
