/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\floor.glb -o .\src\components\Map.jsx 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Map(props) {
  const { nodes, materials } = useGLTF('/models/floor.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Floor_Modular.geometry}
        material={materials.Grey_Floor}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload('/models/floor.glb');
