/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\floor.glb -o .\src\components\Map.jsx 
*/

import * as THREE from 'three';
import { useTexture } from '@react-three/drei';
import { CuboidCollider } from '@react-three/rapier';
import React, { useRef } from 'react';

export function Map(props) {
  const texture = useTexture({ map: '/grass.png' });
  texture.map.wrapS = texture.map.wrapT = THREE.RepeatWrapping;
  return (
    <group {...props} dispose={null}>
      <mesh receiveShadow position={[0, 0, 0]} rotation-x={-Math.PI / 2}>
        <planeGeometry args={[1000, 1000]} />
        <meshStandardMaterial map={texture.map} map-repeat={[240, 240]} color="green" />
      </mesh>
      <CuboidCollider args={[1000, 2, 1000]} position={[0, -2, 0]} />
    </group>
  );
}
